package math.domain;

public enum Sisalto {
    PROSENTTILUKU,
    PROSENTTIARVO,
    LISAANTYNYTARVO,
    VAHENTYNYTARVO,
    MUUTOSPROSENTTI,
    VERTAILUPROSENTTIVAHEMMAN,
    VERTAILUPROSENTTIENEMMAN,
    PERUSARVO,
    KORKO,
    KORKOAKOROLLE,
    SEOS
}
